version: "3"

services:
  geth-bootnode:
    hostname: geth-bootnode
    platform: "linux/amd64"
    environment:
      - nodekeyhex=08f0e1dee5c1b4645f3331a566009e41a4514b6cd28656d63d0449ecf812812b #Needs to be fix, so that the miners know the resulting enode id
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c # enodeId
      - bootnodeIp=172.25.0.101
    build: ./bootnode
    # image: maibornwolff/eden:geth-bootnode
    container_name: geth-bootnode
    ports:
      - 30301:30301/udp
      - 30303:30303/udp
    networks:
      chainnet:
        ipv4_address: 172.25.0.101 # The miners need to know the IP address later on

  geth-dev-miner-1:
    hostname: geth-dev-miner-1
    platform: "linux/amd64"
    depends_on:
      - geth-bootnode
    environment:
      - address=0x8cc5a1a0802db41db826c2fcb72423744338dcb0 #derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
      - nodekeyhex=8eb666d3e8a42bfc7d9e829af60b6d9142d65bef1ecb5897622b4c3ef93377e2
      - minerId= 2ed7d9205ff27bf8fda964e2f11775498844ba300402f5d582fb04e8abdd2266fe0e33b112d53ed1f237713acbe162e6a68949b04344e4cd9f7939b8cb1e8c3e # enodeId
    build:
      context: ./miner
      args:
        privatekey: df504d175ae63abf209bad9dda965310d99559620550e74521a6798a41215f46 # Please don't do something like this in production, okay?
        password: pass
    # image: maibornwolff/eden:geth-dev-miner-1
    container_name: geth-dev-miner-1
    ports:
      - 8541:8545
      - 8542:8546
    healthcheck:
      test: wget http://localhost:8545
      interval: 2s
      timeout: 5s
      retries: 30
    # volumes:
    #   - eth-data-1:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address

  geth-dev-miner-2:
    hostname: geth-dev-miner-2
    platform: "linux/amd64"
    depends_on:
      - geth-bootnode
    environment:
      - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 #derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
      - nodekeyhex=8861389742e9ee2669855a4928a712cec0f275241a359647772df689840c3c6c
      - minerId=166ed53a196caeaf96d78625bfe1ec557ea21d379e77f8e8d177c9851e7a6869e141f65f49a3dd05752a285df01e150154cff056571f339c9967ccbc7d0c7f0a # enodeId
    build:
      context: ./miner
      args:
        privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
        password: word
    # image: maibornwolff/eden:geth-dev-miner-2
    container_name: geth-dev-miner-2
    ports:
      - 8543:8545
      - 8544:8546
    healthcheck:
      test: wget http://localhost:8545
      interval: 2s
      timeout: 5s
      retries: 30
    # volumes:
    #   - eth-data-2:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.104

  
networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
